name: CI/CD Pipeline for Caesar.java

on:
  push:
    branches:
      - main  # Run on push to main branch
  pull_request:
    branches:
      - main  # Run on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Caesar.java
        run: javac Caesar.java

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/caesar-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
     - name: SSH into Server & Deploy
       uses: appleboy/ssh-action@v0.1.5
       with:
         host: ${{ secrets.SERVER_IP }}
         username: ${{ secrets.SERVER_USER }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/caesar-app:latest
          docker stop caesar-app || true
          docker rm caesar-app || true
          docker run -it --name caesar-app ${{ secrets.DOCKER_USERNAME }}/caesar-app:latest
